import type { Metadata } from "next";

import "./globals.css";
import NavigationBer from "@/components/shared/navber";
import { Oswald, Inter } from "next/font/google";
const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${oswald.variable} h-full antialiased`}
    >
      <NavigationBer></NavigationBer>
      <body className="min-h-full flex flex-col bg-[#0f1115]">{children}</body>
    </html>
  );
}
