import type { Metadata } from "next";

import "./globals.css";
import NavigationBar from "@/components/shared/navbar";
import { Oswald, Inter } from "next/font/google";
import Footer from "@/components/shared/footer";
import WorkoutProvider from "./context/workoutprovider";
import { ToastContainer } from "react-toastify";
const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Fit Log",
  icons: { icon: "/favicon.png" },
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${oswald.variable} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col bg-[#0f1115]">
        <WorkoutProvider>
          <NavigationBar></NavigationBar>
          <main className="flex-1">{children}</main>
          <Footer></Footer>
        </WorkoutProvider>
        <ToastContainer theme="dark" />
      </body>
    </html>
  );
}
